// THIS FILE IS AUTOMATICALLY GENERATED. DO NOT MODIFY IT.
import { Document } from '@contentful/rich-text-types'
import { Asset, Entry } from 'contentful'

export interface IIntroductionFields {
	/** logoNassa */
	logoNassa: Asset

	/** welcome */
	welcome: string

	/** text */
	text: string[]
}

/** Messaggio di introduzione (hero section in Home page) */

export interface IIntroduction extends Entry<IIntroductionFields> {
	sys: {
		id: string
		type: string
		createdAt: string
		updatedAt: string
		locale: string
		contentType: {
			sys: {
				id: 'introduction'
				linkType: 'ContentType'
				type: 'Link'
			}
		}
	}
}

export interface IMilestonesFields {
	/** title */
	title: string

	/** description */
	description?: string | undefined

	/** date */
	date?: string | undefined

	/** nassa */
	nassa: INassa[]
}

/** Milestones delle nasse */

export interface IMilestones extends Entry<IMilestonesFields> {
	sys: {
		id: string
		type: string
		createdAt: string
		updatedAt: string
		locale: string
		contentType: {
			sys: {
				id: 'milestones'
				linkType: 'ContentType'
				type: 'Link'
			}
		}
	}
}

export interface INassaFields {
	/** name */
	name: string

	/** id */
	id: string

	/** logo */
	logo?: Asset | undefined
}

/** Modello della nassa */

export interface INassa extends Entry<INassaFields> {
	sys: {
		id: string
		type: string
		createdAt: string
		updatedAt: string
		locale: string
		contentType: {
			sys: {
				id: 'nassa'
				linkType: 'ContentType'
				type: 'Link'
			}
		}
	}
}

export type CONTENT_TYPE = 'introduction' | 'milestones' | 'nassa'

export type LOCALE_CODE = 'en-US'

export type CONTENTFUL_DEFAULT_LOCALE_CODE = 'en-US'
